### ISSUE TITLE
не находятся решения некоторых задач с tfold

### ISSUE THREAD

**Issue by 6zow** [atemerev/icfpc2013#10]
client low-level-solve eHpHVew70mw3Ni5wAzaS2lfK 14 "if0 or shr4 tfold xor"

возвращает 
client: Couldn't find any program matching conditions at all!

training task:
{"id":"eHpHVew70mw3Ni5wAzaS2lfK","size":14,"operators":["if0","or","shr4","tfold","xor"],"challenge":"(lambda (x_17901) (fold x_17901 0 (lambda (x_17901 x_17902) (if0 (xor (or x_17902 (shr4 x_17901)) x_17901) 0 x_17901))))"}

**Comment by adept** [comment]
Task is already solved, i think that it is fixed now
