### ISSUE TITLE
Many mismatches on a problem of size 15

### ISSUE THREAD

**Issue by jkff** [atemerev/icfpc2013#9]
jkff@jkff-laptop ~/projects/icfp/src $ client train-solve 15
TrainingResponse {challenge = "(lambda (x_33456) (fold (or (shr16 (xor x_33456 1)) (shl1 1)) x_33456 (lambda (x_33457 x_33458) (if0 x_33457 x_33458 x_33457))))", trainingId = "dLG8yDzQ3yy02hshLlVntltM", trainingSize = 15, trainingOps = ["fold","if0","or","shl1","shr16","xor"]}
INOUTS to reproduce with client solve-exact: ([9109764189119939331,6818300578044174151,17384048449713003284,409605325706061362,5896917308668905398,7888238219259382178,16847977563828141316,5535784720060370725,2236735494332136231,13305007310275612668,12813318345463711949,5896206253442140688,15670242532607316299,17267917832867093220,1020534779710405241,12048607241385193618,8050865214623055818,6460385167250134506,5469949361724343474,13900646785515303538,162367822234810611,16782850862780625104,15113568662461138522,699314765707889232,7351501933256914050,18391800900785029083,9430308032969041730,4272890966755972521,14738166217524882610,14274200164728402121,14885363007503059341,17456472207701437923,3225410326122351205,6459213743641166859,7580797367843732586,7663857176078843518,4478527059486131213,12378376662003369315,15354084246450356264,3882883807726390485,8695692710834753010,9612475278294686545,8756292412382519860,4023953875220556493,3624953757829680544,13704728917192934170,9055152473692374998,12694988598058410740,11785041346563476755,8187621617660532581,13209388126519854030,17900721523119981773,17387365103990379793,13023023181850877946,3789769884552266239,6422840649999882551,15141815076600841850,3256668531542011966,402812682569450401,4446868586415837719,13979293748908033486,14413650946704745961,7476321478695490084,3721157485248814698,18029761710222983902,14117726028417852376,3628609816196775378,14470150668765230565,5123776047399506968,2549571397483248957,16587337110412553876,12339272725668472151,4117004379808396000,14791885482584327463,10405440487214223138,1592948815897023322,6196009062270336653,10780561495824806783,14106985365625709452,16874533478829127936,16566688090773943874,16021493241635534269,845307299141679943,16227826063753766215,12643054249182853946,13191969057658247962,3009703659274802112,4259552918561117566,11243402591678266843,10300373027177738753,3930645807789290162,1205112057338375197,1571251107214775894,5960876436578427729,11235331530707210286,15927904720559378251,15839307463794914327,9131963102594112395,757378173997257132,16134657786117859154,11384408604927490251,390232248685042934,13593680949761684372,12741539964128139820,5083337212026287612,16664399471484947490,13834207602872333130,3753926933108684011,11907054976582470991,14663593161348462662,16934509335142809396,4482647068477512786,3997076247599085047,4411385983815097934,479498597899910032,3780997616967068493,11820340226744778047,12772596406608939867,8100748625166302472,13219155810526282390,7652929080203591714,2447295463534226323,5611496897307967496,4440317711908497996,8200689210603268046,11228911107880119902,6035132255506830727,548332088033774365,2846934894483365539,15634499949211826688,13202171351297493438,2626484996530692386,13592871211173050353,2335536650086700548,16961443166987011871,1707686047351991230,8564325383416129140,2771218742909638585,842061871819245888,16641837043814470335,15233887220730270906,17233842384441762051,15850560894990331517,10471221706510203418,8873086724818332180,16472545420754125993,17228831829202168346,5741286585111712101,15349059843925799910,12892299508816654510,16507923920343776305,11856918535360392077,17216240799024296381,10794691194333894649,14829914655349315696,11011674496580951562,12651618890162660406,1605362211666599768,2150004139486628836,14896490517577040037,7415994843444664782,2710306386249041729,7659892775242985842,13842886823837780755,10583196171140549871,8898010094212008510,11267840423650837645,6565868223505131969,14877398467661704264,6292906396050747127,9864962151422434275,11707939709210892039,1472410204261744883,1563181947857958051,15553240406090089301,17229604146021725090,3117721099812329424,17985201289148893362,2196378664300962638,5900764870575285083,8833414126218255036,9975665064923276053,12569222922249696033,18224135089547734601,3278213577252361190,6811238552486506425,16967003064463933989,12245513387892274867,16624922249218647909,7518481600035927356,17667007618598055444,12421405785364127407,3342982320803981108,11013369058787406922,15628911968944220173,15036844936004032464,16950459392905218183,13571111612275286542,3479965519173159437,3375550685047252952,13853998344935688275,868911329633201854,16632629313936042975,17074121819172940292,15425714690736508257,362738652099559916,5380109664307420631,4904565595926221562,17226357996190323868,4463810695620296993,14017652576077221496,736602501757696555,4319071050664185973,13001608349995701215,15979605525575777461,4492675470361370162,17443062937383601204,13630014953319525652,12664782076466969796,10692608520074050417,10990461612996652518,4273618016451279452,16550558508459117372,8685098350238065182,13928310764112472718,6789680798840583114,8588823290516450818,13981601747701922529,4329326330583223747,2494794559389713718,4765239106196599472,12972752728703891593,15741393235525467674,4439447296967444141,11795796871789670490,3586918535888598046,9329498881689010051,61292103838955194,11563471008764949276,2334749091286590762,8010202442754767812,10822276890237720697,4124656734127869902,4779001284913326282,7345278995768946380,12966147408129016754,3017588912286082252,17066864098848881518,5024652794665183260,11593506565530278719,11430289357277434977,1050961906281449284,2920399264468913321,2753696974207149099,14698283278342285304,15155631486672701586],[126,94,241,5,81,109,233,76,31,184,177,81,217,239,14,167,111,89,75,192,2,232,209,9,102,255,130,59,204,198,206,242,44,89,105,106,62,171,213,53,120,133,121,55,50,190,125,176,163,113,183,248,241,180,52,89,210,45,5,61,194,200,103,51,250,195,50,200,71,35,230,171,57,205,144,22,85,149,195,234,229,222,11,225,175,183,41,59,156,142,54,16,21,82,155,221,219,126,10,223,157,5,188,176,70,231,191,52,165,203,235,62,55,61,6,52,164,177,112,183,106,33,77,61,113,155,83,7,39,216,183,36,188,32,235,23,118,38,11,230,211,239,219,145,123,228,239,79,213,178,229,164,238,149,205,152,175,22,29,206,102,37,106,192,146,123,156,91,206,87,136,162,20,21,215,239,43,249,30,81,122,138,174,252,45,94,235,169,230,104,245,172,46,152,216,208,235,188,48,46,192,12,230,236,214,5,74,68,239,61,194,10,59,180,221,62,242,189,175,148,152,59,229,120,193,94,119,194,60,34,66,180,218,61,163,49,129,217,160,32,111,150,57,66,101,179,41,236,69,160,158,14,40,38,203,210])
ExpC {cached = MWord64 126, expr = Fold {foldArg = ExpC {cached = MWord64 9109764189119939331, expr = MainArg}, foldSeed = ExpC {cached = MWord64 0, expr = Zero}, foldBody = ExpC {cached = MWord64 1306896099427793925, expr = If {ifCond = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}, ifTrue = ExpC {cached = MWord64 1306896099427793925, expr = Fold2Arg}, ifFalse = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}}}}}
Mismatch on 128 : 128 instead of 2
INOUTS to reproduce with client solve-exact: ([128,9109764189119939331,6818300578044174151,17384048449713003284,409605325706061362,5896917308668905398,7888238219259382178,16847977563828141316,5535784720060370725,2236735494332136231,13305007310275612668,12813318345463711949,5896206253442140688,15670242532607316299,17267917832867093220,1020534779710405241,12048607241385193618,8050865214623055818,6460385167250134506,5469949361724343474,13900646785515303538,162367822234810611,16782850862780625104,15113568662461138522,699314765707889232,7351501933256914050,18391800900785029083,9430308032969041730,4272890966755972521,14738166217524882610,14274200164728402121,14885363007503059341,17456472207701437923,3225410326122351205,6459213743641166859,7580797367843732586,7663857176078843518,4478527059486131213,12378376662003369315,15354084246450356264,3882883807726390485,8695692710834753010,9612475278294686545,8756292412382519860,4023953875220556493,3624953757829680544,13704728917192934170,9055152473692374998,12694988598058410740,11785041346563476755,8187621617660532581,13209388126519854030,17900721523119981773,17387365103990379793,13023023181850877946,3789769884552266239,6422840649999882551,15141815076600841850,3256668531542011966,402812682569450401,4446868586415837719,13979293748908033486,14413650946704745961,7476321478695490084,3721157485248814698,18029761710222983902,14117726028417852376,3628609816196775378,14470150668765230565,5123776047399506968,2549571397483248957,16587337110412553876,12339272725668472151,4117004379808396000,14791885482584327463,10405440487214223138,1592948815897023322,6196009062270336653,10780561495824806783,14106985365625709452,16874533478829127936,16566688090773943874,16021493241635534269,845307299141679943,16227826063753766215,12643054249182853946,13191969057658247962,3009703659274802112,4259552918561117566,11243402591678266843,10300373027177738753,3930645807789290162,1205112057338375197,1571251107214775894,5960876436578427729,11235331530707210286,15927904720559378251,15839307463794914327,9131963102594112395,757378173997257132,16134657786117859154,11384408604927490251,390232248685042934,13593680949761684372,12741539964128139820,5083337212026287612,16664399471484947490,13834207602872333130,3753926933108684011,11907054976582470991,14663593161348462662,16934509335142809396,4482647068477512786,3997076247599085047,4411385983815097934,479498597899910032,3780997616967068493,11820340226744778047,12772596406608939867,8100748625166302472,13219155810526282390,7652929080203591714,2447295463534226323,5611496897307967496,4440317711908497996,8200689210603268046,11228911107880119902,6035132255506830727,548332088033774365,2846934894483365539,15634499949211826688,13202171351297493438,2626484996530692386,13592871211173050353,2335536650086700548,16961443166987011871,1707686047351991230,8564325383416129140,2771218742909638585,842061871819245888,16641837043814470335,15233887220730270906,17233842384441762051,15850560894990331517,10471221706510203418,8873086724818332180,16472545420754125993,17228831829202168346,5741286585111712101,15349059843925799910,12892299508816654510,16507923920343776305,11856918535360392077,17216240799024296381,10794691194333894649,14829914655349315696,11011674496580951562,12651618890162660406,1605362211666599768,2150004139486628836,14896490517577040037,7415994843444664782,2710306386249041729,7659892775242985842,13842886823837780755,10583196171140549871,8898010094212008510,11267840423650837645,6565868223505131969,14877398467661704264,6292906396050747127,9864962151422434275,11707939709210892039,1472410204261744883,1563181947857958051,15553240406090089301,17229604146021725090,3117721099812329424,17985201289148893362,2196378664300962638,5900764870575285083,8833414126218255036,9975665064923276053,12569222922249696033,18224135089547734601,3278213577252361190,6811238552486506425,16967003064463933989,12245513387892274867,16624922249218647909,7518481600035927356,17667007618598055444,12421405785364127407,3342982320803981108,11013369058787406922,15628911968944220173,15036844936004032464,16950459392905218183,13571111612275286542,3479965519173159437,3375550685047252952,13853998344935688275,868911329633201854,16632629313936042975,17074121819172940292,15425714690736508257,362738652099559916,5380109664307420631,4904565595926221562,17226357996190323868,4463810695620296993,14017652576077221496,736602501757696555,4319071050664185973,13001608349995701215,15979605525575777461,4492675470361370162,17443062937383601204,13630014953319525652,12664782076466969796,10692608520074050417,10990461612996652518,4273618016451279452,16550558508459117372,8685098350238065182,13928310764112472718,6789680798840583114,8588823290516450818,13981601747701922529,4329326330583223747,2494794559389713718,4765239106196599472,12972752728703891593,15741393235525467674,4439447296967444141,11795796871789670490,3586918535888598046,9329498881689010051,61292103838955194,11563471008764949276,2334749091286590762,8010202442754767812,10822276890237720697,4124656734127869902,4779001284913326282,7345278995768946380,12966147408129016754,3017588912286082252,17066864098848881518,5024652794665183260,11593506565530278719,11430289357277434977,1050961906281449284,2920399264468913321,2753696974207149099,14698283278342285304,15155631486672701586],[2,126,94,241,5,81,109,233,76,31,184,177,81,217,239,14,167,111,89,75,192,2,232,209,9,102,255,130,59,204,198,206,242,44,89,105,106,62,171,213,53,120,133,121,55,50,190,125,176,163,113,183,248,241,180,52,89,210,45,5,61,194,200,103,51,250,195,50,200,71,35,230,171,57,205,144,22,85,149,195,234,229,222,11,225,175,183,41,59,156,142,54,16,21,82,155,221,219,126,10,223,157,5,188,176,70,231,191,52,165,203,235,62,55,61,6,52,164,177,112,183,106,33,77,61,113,155,83,7,39,216,183,36,188,32,235,23,118,38,11,230,211,239,219,145,123,228,239,79,213,178,229,164,238,149,205,152,175,22,29,206,102,37,106,192,146,123,156,91,206,87,136,162,20,21,215,239,43,249,30,81,122,138,174,252,45,94,235,169,230,104,245,172,46,152,216,208,235,188,48,46,192,12,230,236,214,5,74,68,239,61,194,10,59,180,221,62,242,189,175,148,152,59,229,120,193,94,119,194,60,34,66,180,218,61,163,49,129,217,160,32,111,150,57,66,101,179,41,236,69,160,158,14,40,38,203,210])
ExpC {cached = MWord64 126, expr = Fold {foldArg = ExpC {cached = MWord64 139003970170897, expr = Shr16 (ExpC {cached = MWord64 9109764189119939331, expr = MainArg})}, foldSeed = ExpC {cached = MWord64 2, expr = Shl1 (ExpC {cached = MWord64 1, expr = One})}, foldBody = ExpC {cached = MWord64 1306896099427793925, expr = If {ifCond = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}, ifTrue = ExpC {cached = MWord64 1306896099427793925, expr = Fold2Arg}, ifFalse = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}}}}}
Mismatch on 262144 : 4 instead of 6
INOUTS to reproduce with client solve-exact: ([262144,128,9109764189119939331,6818300578044174151,17384048449713003284,409605325706061362,5896917308668905398,7888238219259382178,16847977563828141316,5535784720060370725,2236735494332136231,13305007310275612668,12813318345463711949,5896206253442140688,15670242532607316299,17267917832867093220,1020534779710405241,12048607241385193618,8050865214623055818,6460385167250134506,5469949361724343474,13900646785515303538,162367822234810611,16782850862780625104,15113568662461138522,699314765707889232,7351501933256914050,18391800900785029083,9430308032969041730,4272890966755972521,14738166217524882610,14274200164728402121,14885363007503059341,17456472207701437923,3225410326122351205,6459213743641166859,7580797367843732586,7663857176078843518,4478527059486131213,12378376662003369315,15354084246450356264,3882883807726390485,8695692710834753010,9612475278294686545,8756292412382519860,4023953875220556493,3624953757829680544,13704728917192934170,9055152473692374998,12694988598058410740,11785041346563476755,8187621617660532581,13209388126519854030,17900721523119981773,17387365103990379793,13023023181850877946,3789769884552266239,6422840649999882551,15141815076600841850,3256668531542011966,402812682569450401,4446868586415837719,13979293748908033486,14413650946704745961,7476321478695490084,3721157485248814698,18029761710222983902,14117726028417852376,3628609816196775378,14470150668765230565,5123776047399506968,2549571397483248957,16587337110412553876,12339272725668472151,4117004379808396000,14791885482584327463,10405440487214223138,1592948815897023322,6196009062270336653,10780561495824806783,14106985365625709452,16874533478829127936,16566688090773943874,16021493241635534269,845307299141679943,16227826063753766215,12643054249182853946,13191969057658247962,3009703659274802112,4259552918561117566,11243402591678266843,10300373027177738753,3930645807789290162,1205112057338375197,1571251107214775894,5960876436578427729,11235331530707210286,15927904720559378251,15839307463794914327,9131963102594112395,757378173997257132,16134657786117859154,11384408604927490251,390232248685042934,13593680949761684372,12741539964128139820,5083337212026287612,16664399471484947490,13834207602872333130,3753926933108684011,11907054976582470991,14663593161348462662,16934509335142809396,4482647068477512786,3997076247599085047,4411385983815097934,479498597899910032,3780997616967068493,11820340226744778047,12772596406608939867,8100748625166302472,13219155810526282390,7652929080203591714,2447295463534226323,5611496897307967496,4440317711908497996,8200689210603268046,11228911107880119902,6035132255506830727,548332088033774365,2846934894483365539,15634499949211826688,13202171351297493438,2626484996530692386,13592871211173050353,2335536650086700548,16961443166987011871,1707686047351991230,8564325383416129140,2771218742909638585,842061871819245888,16641837043814470335,15233887220730270906,17233842384441762051,15850560894990331517,10471221706510203418,8873086724818332180,16472545420754125993,17228831829202168346,5741286585111712101,15349059843925799910,12892299508816654510,16507923920343776305,11856918535360392077,17216240799024296381,10794691194333894649,14829914655349315696,11011674496580951562,12651618890162660406,1605362211666599768,2150004139486628836,14896490517577040037,7415994843444664782,2710306386249041729,7659892775242985842,13842886823837780755,10583196171140549871,8898010094212008510,11267840423650837645,6565868223505131969,14877398467661704264,6292906396050747127,9864962151422434275,11707939709210892039,1472410204261744883,1563181947857958051,15553240406090089301,17229604146021725090,3117721099812329424,17985201289148893362,2196378664300962638,5900764870575285083,8833414126218255036,9975665064923276053,12569222922249696033,18224135089547734601,3278213577252361190,6811238552486506425,16967003064463933989,12245513387892274867,16624922249218647909,7518481600035927356,17667007618598055444,12421405785364127407,3342982320803981108,11013369058787406922,15628911968944220173,15036844936004032464,16950459392905218183,13571111612275286542,3479965519173159437,3375550685047252952,13853998344935688275,868911329633201854,16632629313936042975,17074121819172940292,15425714690736508257,362738652099559916,5380109664307420631,4904565595926221562,17226357996190323868,4463810695620296993,14017652576077221496,736602501757696555,4319071050664185973,13001608349995701215,15979605525575777461,4492675470361370162,17443062937383601204,13630014953319525652,12664782076466969796,10692608520074050417,10990461612996652518,4273618016451279452,16550558508459117372,8685098350238065182,13928310764112472718,6789680798840583114,8588823290516450818,13981601747701922529,4329326330583223747,2494794559389713718,4765239106196599472,12972752728703891593,15741393235525467674,4439447296967444141,11795796871789670490,3586918535888598046,9329498881689010051,61292103838955194,11563471008764949276,2334749091286590762,8010202442754767812,10822276890237720697,4124656734127869902,4779001284913326282,7345278995768946380,12966147408129016754,3017588912286082252,17066864098848881518,5024652794665183260,11593506565530278719,11430289357277434977,1050961906281449284,2920399264468913321,2753696974207149099,14698283278342285304,15155631486672701586],[6,2,126,94,241,5,81,109,233,76,31,184,177,81,217,239,14,167,111,89,75,192,2,232,209,9,102,255,130,59,204,198,206,242,44,89,105,106,62,171,213,53,120,133,121,55,50,190,125,176,163,113,183,248,241,180,52,89,210,45,5,61,194,200,103,51,250,195,50,200,71,35,230,171,57,205,144,22,85,149,195,234,229,222,11,225,175,183,41,59,156,142,54,16,21,82,155,221,219,126,10,223,157,5,188,176,70,231,191,52,165,203,235,62,55,61,6,52,164,177,112,183,106,33,77,61,113,155,83,7,39,216,183,36,188,32,235,23,118,38,11,230,211,239,219,145,123,228,239,79,213,178,229,164,238,149,205,152,175,22,29,206,102,37,106,192,146,123,156,91,206,87,136,162,20,21,215,239,43,249,30,81,122,138,174,252,45,94,235,169,230,104,245,172,46,152,216,208,235,188,48,46,192,12,230,236,214,5,74,68,239,61,194,10,59,180,221,62,242,189,175,148,152,59,229,120,193,94,119,194,60,34,66,180,218,61,163,49,129,217,160,32,111,150,57,66,101,179,41,236,69,160,158,14,40,38,203,210])
^C

**Comment by adept** [comment]
Got much better:
$ client low-level-solve dLG8yDzQ3yy02hshLlVntltM 15 "fold if0 or shl1 shr16 xor"
INOUTS saved into script dLG8yDzQ3yy02hshLlVntltM.solve-exact
RESTRICTION: allowed left/right zeros: (56,0)
ExpC {cached = MWord64 126, expr = Fold {foldArg = ExpC {cached = MWord64 9109764189119939331, expr = MainArg}, foldSeed = ExpC {cached = MWord64 0, expr = Zero}, foldBody = ExpC {cached = MWord64 1306896099427793925, expr = If {ifCond = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}, ifTrue = ExpC {cached = MWord64 1306896099427793925, expr = Fold2Arg}, ifFalse = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}}}}}
Mismatch on 128 : 128 instead of 2
INOUTS saved into script dLG8yDzQ3yy02hshLlVntltM.solve-exact
RESTRICTION: allowed left/right zeros: (56,0)
ExpC {cached = MWord64 126, expr = Fold {foldArg = ExpC {cached = MWord64 139003970170897, expr = Shr16 (ExpC {cached = MWord64 9109764189119939331, expr = MainArg})}, foldSeed = ExpC {cached = MWord64 2, expr = Shl1 (ExpC {cached = MWord64 1, expr = One})}, foldBody = ExpC {cached = MWord64 1306896099427793925, expr = If {ifCond = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}, ifTrue = ExpC {cached = MWord64 1306896099427793925, expr = Fold2Arg}, ifFalse = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}}}}}
Mismatch on 262144 : 4 instead of 6
INOUTS saved into script dLG8yDzQ3yy02hshLlVntltM.solve-exact
RESTRICTION: allowed left/right zeros: (56,0)
ExpC {cached = MWord64 126, expr = Fold {foldArg = ExpC {cached = MWord64 139003970170899, expr = Or (ExpC {cached = MWord64 2, expr = Shl1 (ExpC {cached = MWord64 1, expr = One})}) (ExpC {cached = MWord64 139003970170897, expr = Shr16 (ExpC {cached = MWord64 9109764189119939331, expr = MainArg})})}, foldSeed = ExpC {cached = MWord64 0, expr = Zero}, foldBody = ExpC {cached = MWord64 1306896099427793925, expr = If {ifCond = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}, ifTrue = ExpC {cached = MWord64 1306896099427793925, expr = Fold2Arg}, ifFalse = ExpC {cached = MWord64 1306896099427793925, expr = Fold1Arg}}}}}
Win
